# Random Forest Classification

## Importing the libraries

In [183]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [184]:
wines = pd.read_csv('winequality-red.csv')
X = wines.iloc[:, [0, 1, 2, 6, 8, 10]].values
# X = wines.iloc[:, :-1].values
y = wines.iloc[:, -1].values


## Spliting the dataset into the Training set and Test set

In [185]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [186]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Applying Random Forest Classification

In [187]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

## Predicting the Test set results

In [188]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[6 6]
 [5 5]
 [7 7]
 [5 6]
 [5 5]
 [6 6]
 [5 5]
 [6 6]
 [5 4]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [6 5]
 [5 6]
 [6 6]
 [7 7]
 [5 5]
 [5 5]
 [6 4]
 [6 7]
 [5 6]
 [6 6]
 [6 4]
 [5 6]
 [5 5]
 [5 5]
 [6 7]
 [5 5]
 [6 6]
 [6 5]
 [6 6]
 [6 5]
 [5 6]
 [7 7]
 [7 7]
 [5 5]
 [5 6]
 [6 6]
 [6 7]
 [5 5]
 [6 7]
 [7 6]
 [7 6]
 [6 5]
 [5 5]
 [5 6]
 [6 6]
 [5 6]
 [6 5]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [7 6]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [6 6]
 [6 6]
 [5 4]
 [6 6]
 [6 5]
 [6 6]
 [5 5]
 [5 5]
 [5 5]
 [6 6]
 [6 6]
 [5 5]
 [6 6]
 [7 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [6 5]
 [5 5]
 [5 5]
 [6 6]
 [6 4]
 [6 5]
 [7 7]
 [6 6]
 [7 6]
 [5 5]
 [5 6]
 [6 5]
 [7 8]
 [6 6]
 [6 6]
 [6 6]
 [6 5]
 [5 5]
 [6 5]
 [5 5]
 [6 7]
 [5 5]
 [6 6]
 [5 5]
 [8 7]
 [5 5]
 [6 6]
 [6 6]
 [5 6]
 [6 7]
 [6 6]
 [6 6]
 [5 5]
 [6 7]
 [5 5]
 [5 5]
 [6 6]
 [7 6]
 [5 5]
 [5 5]
 [6 5]
 [6 6]
 [5 6]
 [5 6]
 [6 6]
 [5 6]
 [6 6]
 [5 5]
 [6 6]
 [5 5]
 [6 8]
 [5 5]
 [6 6]
 [5 5]
 [5 6]

## Confusion Matrix and Accuracy Score

In [189]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm, end="\n\n")
print(f"Accuracy score: {accuracy_score(y_test, y_pred)}")
print()
print(classification_report(y_test, y_pred))

[[  0   0   2   0   0   0]
 [  0   0   8   6   0   0]
 [  0   0 126  39   4   0]
 [  0   0  34 120  16   0]
 [  0   0   3  16  19   2]
 [  0   0   0   4   1   0]]

Accuracy score: 0.6625

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00        14
           5       0.73      0.75      0.74       169
           6       0.65      0.71      0.68       170
           7       0.47      0.47      0.48        40
           8       0.00      0.00      0.00         5

    accuracy                           0.66       400
   macro avg       0.31      0.32      0.31       400
weighted avg       0.63      0.66      0.65       400



c:\Users\tamim\Desktop\BCIT\Term_4\ACIT4880\virtual_environment\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\tamim\Desktop\BCIT\Term_4\ACIT4880\virtual_environment\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\tamim\Desktop\BCIT\Term_4\ACIT4880\virtual_environment\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this beh

## Now we'll divide wine by good and bad quality

In [168]:
wines = pd.read_csv('winequality-red.csv')
bins = (2, 6.5, 8)
group_names = ['bad', 'good']
wines['quality'] = pd.cut(wines['quality'], bins = bins, labels = group_names)

from sklearn.preprocessing import LabelEncoder

label_quality = LabelEncoder()

wines["quality"] = label_quality.fit_transform(wines["quality"])
wines["quality"].value_counts()

0    1382
1     217
Name: quality, dtype: int64

## Now we'll train the model again to predict good and bad quality

In [169]:
X = wines.drop('quality', axis = 1)
y = wines['quality']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

quality_classifier = RandomForestClassifier(n_estimators = 200)
quality_classifier.fit(X_train, y_train)
y_pred = quality_classifier.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(f"Accuracy score: {accuracy_score(y_test, y_pred)}")

              precision    recall  f1-score   support

           0       0.91      0.97      0.94       273
           1       0.74      0.43      0.54        47

    accuracy                           0.89       320
   macro avg       0.82      0.70      0.74       320
weighted avg       0.88      0.89      0.88       320

[[266   7]
 [ 27  20]]
Accuracy score: 0.89375
